release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -16,6 +16,9 @@ on:
         description: 'release version in format 7.y.z'
         required: true
 
+env:
+  IMAGE: quay.io/prabhav/che-plugin-registry
+
 jobs:
   release-build-publish:
     runs-on: ubuntu-latest
@@ -24,7 +27,10 @@ jobs:
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
-
+      - name: "Set up QEMU"
+        uses: docker/setup-qemu-action@v1
+      - name: "Set up Docker Buildx ${{ matrix.arch }}"
+        uses: docker/setup-buildx-action@v1
       - name: Login to Quay.io
         uses: azure/docker-login@v1
         with:
@@ -62,6 +68,83 @@ jobs:
           restore-keys: |
             download-unpacked-cache-
 
+      - name: image-build
+        run: |
+          docker pull quay.io/eclipse/che-plugin-registry:nightly
+          BUILDER=docker SKIP_FORMAT=true SKIP_LINT=true SKIP_TEST=true ./build.sh --tag ${{ github.event.inputs.version }} --platform ${{ matrix.arch }} --buildx --push
+
+      - id: result
+        name: "Build result outputs version"
+        if: ${{ success() }}
+        run: echo "::set-output name=${{ matrix.arch }}::${{ env.VERSION }}-${{ matrix.arch }}"
+
+  create-manifest:
+  needs: build
+  runs-on: ubuntu-latest
+  steps:
+    -
+      name: "Checkout source code"
+      uses: actions/checkout@v1
+      with:
+        fetch-depth: 0
+    - 
+      name: Prepare
+      id: prep
+      run: |
+        SHORT_SHA1=$(git rev-parse --short HEAD)
+        echo ::set-output name=short_sha1::${SHORT_SHA1}
+    -
+      name: "Docker quay.io Login"
+      uses: docker/login-action@v1
+      with:
+        registry: quay.io
+        username: ${{ secrets.QUAY_USERNAME }}
+        password: ${{ secrets.QUAY_PASSWORD }}
+    - 
+      name: Login to docker.io
+      uses: docker/login-action@v1
+      with:
+        registry: docker.io
+        username: ${{ secrets.DOCKERHUB_USERNAME }}
+        password: ${{ secrets.DOCKERHUB_PASSWORD }}
+    -
+      name: "Create and push manifest"
+      run: |
+        AMD64_VERSION="${{ needs['build-images'].outputs.amd64 }}"
+        ARM64_VERSION="${{ needs['build-images'].outputs.arm64 }}"
+        PPC64LE_VERSION="${{ needs['build-images'].outputs.ppc64le }}"
+        S390X_VERSION="${{ needs['build-images'].outputs.s390x }}"
+        if [[ -z "$AMD64_VERSION" || \
+             -z "$ARM64_VERSION" || \
+             -z "$PPC64LE_VERSION" || \
+             -z "$S390X_VERSION" ]]; then
+            echo "[!] The job 'build-images' fails on some of the architectures. Can't create complete manifest.";
+            exit 1;
+        fi
+        AMEND=""
+        AMEND+=" --amend ${{ env.IMAGE }}:$AMD64_VERSION";
+        AMEND+=" --amend ${{ env.IMAGE }}:$ARM64_VERSION";
+        AMEND+=" --amend ${{ env.IMAGE }}:$PPC64LE_VERSION";
+        AMEND+=" --amend ${{ env.IMAGE }}:$S390X_VERSION";
+        docker manifest create ${{ env.IMAGE }}:${{ github.event.inputs.version }} $AMEND
+        docker manifest push ${{ env.IMAGE }}:${{ github.event.inputs.version }}
+        docker manifest create ${{ env.IMAGE }}:${{ steps.prep.outputs.short_sha1 }} $AMEND
+        docker manifest push ${{ env.IMAGE }}:${{ steps.prep.outputs.short_sha1 }}
+    -
+      id: result
+      name: "Manifest result"
+      if: ${{ success() }}
+      run: echo "Manifest was created and pushed successfully"
+    
+  tag-release:
+    needs: create-manifest
+    runs-on: ubuntu-latest
+    steps:
+      -
+        name: "Checkout source code"
+        uses: actions/checkout@v1
+        with:
+          fetch-depth: 0
       - name: Perform release
         run: |
           git config --global user.name "Mykhailo Kuznietsov"
@@ -69,7 +152,7 @@ jobs:
 
           export GITHUB_TOKEN=${{ secrets.CHE_BOT_GITHUB_TOKEN }}
 
-          ./make-release.sh --version ${{ github.event.inputs.version}} --trigger-release
+          ./make-release.sh --version ${{ github.event.inputs.version}} --tag-release
       - name: Create MM message
         run: |
           echo "{\"text\":\":building_construction: Che Plugin Registry ${{ github.event.inputs.version }} has been released: https://quay.io/eclipse/che-plugin-registry:${{ github.event.inputs.version }}\"}" > mattermost.json
